OLED_ENABLE = yes
OLED_TIMEOUT = 0
OLED_DRIVER = SSD1306


RGB_MATRIX_SUPPORTED = yes

AUTO_SHIFT_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
UNICODE_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

COMBO_ENABLE = yes

BOOTLOADER = atmel-dfu

BOOTMAGIC_ENABLE = no
LTO_ENABLE = yes

WPM_ENABLE = yes